from abaqus import *
from abaqusConstants import *
import sketch
import part
import mesh
import section
import regionToolset
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
Hutprofil = mdb.Model(modelType=STANDARD_EXPLICIT, name='Hutprofil')
aHutprofil = Hutprofil.rootAssembly
S1_U_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_1', sheetSize=250.0)
S1_U_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_U_R1_sketch.FixedConstraint(entity=S1_U_R1_sketch.geometry[2])
S1_U_R1_g1=S1_U_R1_sketch.Line(point1=(25,215),point2=(53.45,215))
S1_U_R1_g2=S1_U_R1_sketch.Line(point1=(53.45,215),point2=(64.9,216.01))
S1_U_R1_g3=S1_U_R1_sketch.Line(point1=(64.9,216.01),point2=(63.95,230.13))
S1_U_R1_g4=S1_U_R1_sketch.Line(point1=(63.95,230.13),point2=(57,256))
S1_U_R1_g5=S1_U_R1_sketch.Line(point1=(57,256),point2=(25,256))
S1_U_R1_g6=S1_U_R1_sketch.Line(point1=(25,256),point2=(25,215))
S1_U_R1_sketch.FilletByRadius(radius=5,curve1=S1_U_R1_g1, nearPoint1=(25,215),curve2=S1_U_R1_g2, nearPoint2=(64.9,216.01))
S1_U_R1_sketch.FilletByRadius(radius=0.5,curve1=S1_U_R1_g2, nearPoint1=(53.45,215),curve2=S1_U_R1_g3, nearPoint2=(63.95,230.13))
S1_U_R1_sketch.FilletByRadius(radius=11,curve1=S1_U_R1_g3, nearPoint1=(64.9,216.01),curve2=S1_U_R1_g4, nearPoint2=(57,256))
S1_U_R1_sketch.FilletByRadius(radius=0.5,curve1=S1_U_R1_g4, nearPoint1=(63.95,230.13),curve2=S1_U_R1_g5, nearPoint2=(25,256))
S1_U_R1=Hutprofil.Part(name='S1_U_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_U_R1.AnalyticRigidSurfRevolve(sketch=S1_U_R1_sketch)
aS1_U_R1 = aHutprofil.Instance(name='aS1_U_R1', part=S1_U_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_U_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_U_R1', ), vector=(275 , 294.5, 0))
S1_U_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_2', sheetSize=250.0)
S1_U_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_U_R2_sketch.FixedConstraint(entity=S1_U_R2_sketch.geometry[2])
S1_U_R2_g1=S1_U_R2_sketch.Line(point1=(25,256),point2=(57,256))
S1_U_R2_g2=S1_U_R2_sketch.Line(point1=(57,256),point2=(57,289))
S1_U_R2_g3=S1_U_R2_sketch.Line(point1=(57,289),point2=(25,289))
S1_U_R2_g4=S1_U_R2_sketch.Line(point1=(25,289),point2=(25,256))
S1_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S1_U_R2_g1, nearPoint1=(25,256),curve2=S1_U_R2_g2, nearPoint2=(57,289))
S1_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S1_U_R2_g2, nearPoint1=(57,256),curve2=S1_U_R2_g3, nearPoint2=(25,289))
S1_U_R2=Hutprofil.Part(name='S1_U_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_U_R2.AnalyticRigidSurfRevolve(sketch=S1_U_R2_sketch)
aS1_U_R2 = aHutprofil.Instance(name='aS1_U_R2', part=S1_U_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_U_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_U_R2', ), vector=(275 , 294.5, 0))
S1_U_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_3', sheetSize=250.0)
S1_U_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_U_R3_sketch.FixedConstraint(entity=S1_U_R3_sketch.geometry[2])
S1_U_R3_g1=S1_U_R3_sketch.Line(point1=(25,289),point2=(57,289))
S1_U_R3_g2=S1_U_R3_sketch.Line(point1=(57,289),point2=(62.84,305.01))
S1_U_R3_g3=S1_U_R3_sketch.Line(point1=(62.84,305.01),point2=(63.47,314.05))
S1_U_R3_g4=S1_U_R3_sketch.Line(point1=(63.47,314.05),point2=(52.64,315))
S1_U_R3_g5=S1_U_R3_sketch.Line(point1=(52.64,315),point2=(25,315))
S1_U_R3_g6=S1_U_R3_sketch.Line(point1=(25,315),point2=(25,289))
S1_U_R3_sketch.FilletByRadius(radius=0.5,curve1=S1_U_R3_g1, nearPoint1=(25,289),curve2=S1_U_R3_g2, nearPoint2=(62.84,305.01))
S1_U_R3_sketch.FilletByRadius(radius=9,curve1=S1_U_R3_g2, nearPoint1=(57,289),curve2=S1_U_R3_g3, nearPoint2=(63.47,314.05))
S1_U_R3_sketch.FilletByRadius(radius=0.5,curve1=S1_U_R3_g3, nearPoint1=(62.84,305.01),curve2=S1_U_R3_g4, nearPoint2=(52.64,315))
S1_U_R3_sketch.FilletByRadius(radius=5,curve1=S1_U_R3_g4, nearPoint1=(63.47,314.05),curve2=S1_U_R3_g5, nearPoint2=(25,315))
S1_U_R3=Hutprofil.Part(name='S1_U_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_U_R3.AnalyticRigidSurfRevolve(sketch=S1_U_R3_sketch)
aS1_U_R3 = aHutprofil.Instance(name='aS1_U_R3', part=S1_U_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_U_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_U_R3', ), vector=(275 , 294.5, 0))
S1_O_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_4', sheetSize=250.0)
S1_O_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_O_R1_sketch.FixedConstraint(entity=S1_O_R1_sketch.geometry[2])
S1_O_R1_g1=S1_O_R1_sketch.Line(point1=(25,196),point2=(84.3,196))
S1_O_R1_g2=S1_O_R1_sketch.Line(point1=(84.3,196),point2=(94.63,213.89))
S1_O_R1_g3=S1_O_R1_sketch.Line(point1=(94.63,213.89),point2=(70.5,216))
S1_O_R1_g4=S1_O_R1_sketch.Line(point1=(70.5,216),point2=(25,216))
S1_O_R1_g5=S1_O_R1_sketch.Line(point1=(25,216),point2=(25,196))
S1_O_R1_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R1_g1, nearPoint1=(25,196),curve2=S1_O_R1_g2, nearPoint2=(94.63,213.89))
S1_O_R1_sketch.FilletByRadius(radius=2.5,curve1=S1_O_R1_g2, nearPoint1=(84.3,196),curve2=S1_O_R1_g3, nearPoint2=(70.5,216))
S1_O_R1_sketch.FilletByRadius(radius=0.48,curve1=S1_O_R1_g3, nearPoint1=(94.63,213.89),curve2=S1_O_R1_g4, nearPoint2=(25,216))
S1_O_R1=Hutprofil.Part(name='S1_O_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_O_R1.AnalyticRigidSurfRevolve(sketch=S1_O_R1_sketch)
aS1_O_R1 = aHutprofil.Instance(name='aS1_O_R1', part=S1_O_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_O_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_O_R1', ), vector=(275, 432.5, 0))
S1_O_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_5', sheetSize=250.0)
S1_O_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_O_R2_sketch.FixedConstraint(entity=S1_O_R2_sketch.geometry[2])
S1_O_R2_g1=S1_O_R2_sketch.Line(point1=(25,216),point2=(71.07,216))
S1_O_R2_g2=S1_O_R2_sketch.Line(point1=(71.07,216),point2=(73,238))
S1_O_R2_g3=S1_O_R2_sketch.Line(point1=(73,238),point2=(25,238))
S1_O_R2_g4=S1_O_R2_sketch.Line(point1=(25,238),point2=(25,216))
S1_O_R2_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R2_g1, nearPoint1=(25,216),curve2=S1_O_R2_g2, nearPoint2=(73,238))
S1_O_R2_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R2_g2, nearPoint1=(71.07,216),curve2=S1_O_R2_g3, nearPoint2=(25,238))
S1_O_R2=Hutprofil.Part(name='S1_O_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_O_R2.AnalyticRigidSurfRevolve(sketch=S1_O_R2_sketch)
aS1_O_R2 = aHutprofil.Instance(name='aS1_O_R2', part=S1_O_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_O_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_O_R2', ), vector=(275, 432.5, 0))
S1_O_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_6', sheetSize=250.0)
S1_O_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_O_R3_sketch.FixedConstraint(entity=S1_O_R3_sketch.geometry[2])
S1_O_R3_g1=S1_O_R3_sketch.Line(point1=(25,250.9),point2=(79.5,250.9))
S1_O_R3_g2=S1_O_R3_sketch.Line(point1=(79.5,250.9),point2=(79.5,265.9))
S1_O_R3_g3=S1_O_R3_sketch.Line(point1=(79.5,265.9),point2=(25,265.9))
S1_O_R3_g4=S1_O_R3_sketch.Line(point1=(25,265.9),point2=(25,250.9))
S1_O_R3_sketch.FilletByRadius(radius=6.5,curve1=S1_O_R3_g1, nearPoint1=(25,250.9),curve2=S1_O_R3_g2, nearPoint2=(79.5,265.9))
S1_O_R3_sketch.FilletByRadius(radius=1,curve1=S1_O_R3_g2, nearPoint1=(79.5,250.9),curve2=S1_O_R3_g3, nearPoint2=(25,265.9))
S1_O_R3=Hutprofil.Part(name='S1_O_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_O_R3.AnalyticRigidSurfRevolve(sketch=S1_O_R3_sketch)
aS1_O_R3 = aHutprofil.Instance(name='aS1_O_R3', part=S1_O_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_O_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_O_R3', ), vector=(275, 432.5, 0))
S1_O_R4_sketch=Hutprofil.ConstrainedSketch(name='Sketch_7', sheetSize=250.0)
S1_O_R4_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_O_R4_sketch.FixedConstraint(entity=S1_O_R4_sketch.geometry[2])
S1_O_R4_g1=S1_O_R4_sketch.Line(point1=(25,278.9),point2=(79.5,278.9))
S1_O_R4_g2=S1_O_R4_sketch.Line(point1=(79.5,278.9),point2=(79.5,293.9))
S1_O_R4_g3=S1_O_R4_sketch.Line(point1=(79.5,293.9),point2=(25,293.9))
S1_O_R4_g4=S1_O_R4_sketch.Line(point1=(25,293.9),point2=(25,278.9))
S1_O_R4_sketch.FilletByRadius(radius=1,curve1=S1_O_R4_g1, nearPoint1=(25,278.9),curve2=S1_O_R4_g2, nearPoint2=(79.5,293.9))
S1_O_R4_sketch.FilletByRadius(radius=6.5,curve1=S1_O_R4_g2, nearPoint1=(79.5,278.9),curve2=S1_O_R4_g3, nearPoint2=(25,293.9))
S1_O_R4=Hutprofil.Part(name='S1_O_R4',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_O_R4.AnalyticRigidSurfRevolve(sketch=S1_O_R4_sketch)
aS1_O_R4 = aHutprofil.Instance(name='aS1_O_R4', part=S1_O_R4,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_O_R4', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_O_R4', ), vector=(275, 432.5, 0))
S1_O_R5_sketch=Hutprofil.ConstrainedSketch(name='Sketch_8', sheetSize=250.0)
S1_O_R5_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_O_R5_sketch.FixedConstraint(entity=S1_O_R5_sketch.geometry[2])
S1_O_R5_g1=S1_O_R5_sketch.Line(point1=(25,297.4),point2=(61.46,297.4))
S1_O_R5_g2=S1_O_R5_sketch.Line(point1=(61.46,297.4),point2=(74.17,298.51))
S1_O_R5_g3=S1_O_R5_sketch.Line(point1=(74.17,298.51),point2=(72.83,313.9))
S1_O_R5_g4=S1_O_R5_sketch.Line(point1=(72.83,313.9),point2=(25,313.9))
S1_O_R5_g5=S1_O_R5_sketch.Line(point1=(25,313.9),point2=(25,297.4))
S1_O_R5_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R5_g1, nearPoint1=(25,297.4),curve2=S1_O_R5_g2, nearPoint2=(74.17,298.51))
S1_O_R5_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R5_g2, nearPoint1=(61.46,297.4),curve2=S1_O_R5_g3, nearPoint2=(72.83,313.9))
S1_O_R5_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R5_g3, nearPoint1=(74.17,298.51),curve2=S1_O_R5_g4, nearPoint2=(25,313.9))
S1_O_R5=Hutprofil.Part(name='S1_O_R5',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_O_R5.AnalyticRigidSurfRevolve(sketch=S1_O_R5_sketch)
aS1_O_R5 = aHutprofil.Instance(name='aS1_O_R5', part=S1_O_R5,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_O_R5', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_O_R5', ), vector=(275, 432.5, 0))
S1_O_R6_sketch=Hutprofil.ConstrainedSketch(name='Sketch_9', sheetSize=250.0)
S1_O_R6_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S1_O_R6_sketch.FixedConstraint(entity=S1_O_R6_sketch.geometry[2])
S1_O_R6_g1=S1_O_R6_sketch.Line(point1=(25,313.9),point2=(71,313.9))
S1_O_R6_g2=S1_O_R6_sketch.Line(point1=(71,313.9),point2=(97.59,316.23))
S1_O_R6_g3=S1_O_R6_sketch.Line(point1=(97.59,316.23),point2=(75.64,328.9))
S1_O_R6_g4=S1_O_R6_sketch.Line(point1=(75.64,328.9),point2=(25,328.9))
S1_O_R6_g5=S1_O_R6_sketch.Line(point1=(25,328.9),point2=(25,313.9))
S1_O_R6_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R6_g1, nearPoint1=(25,313.9),curve2=S1_O_R6_g2, nearPoint2=(97.59,316.23))
S1_O_R6_sketch.FilletByRadius(radius=2,curve1=S1_O_R6_g2, nearPoint1=(71,313.9),curve2=S1_O_R6_g3, nearPoint2=(75.64,328.9))
S1_O_R6_sketch.FilletByRadius(radius=0.5,curve1=S1_O_R6_g3, nearPoint1=(97.59,316.23),curve2=S1_O_R6_g4, nearPoint2=(25,328.9))
S1_O_R6=Hutprofil.Part(name='S1_O_R6',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S1_O_R6.AnalyticRigidSurfRevolve(sketch=S1_O_R6_sketch)
aS1_O_R6 = aHutprofil.Instance(name='aS1_O_R6', part=S1_O_R6,dependent=ON)
aHutprofil.rotate(instanceList=('aS1_O_R6', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS1_O_R6', ), vector=(275, 432.5, 0))
S2_U_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_10', sheetSize=250.0)
S2_U_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_U_R1_sketch.FixedConstraint(entity=S2_U_R1_sketch.geometry[2])
S2_U_R1_g1=S2_U_R1_sketch.Line(point1=(25,217),point2=(58.52,217))
S2_U_R1_g2=S2_U_R1_sketch.Line(point1=(58.52,217),point2=(74.68,219.85))
S2_U_R1_g3=S2_U_R1_sketch.Line(point1=(74.68,219.85),point2=(72.46,233.85))
S2_U_R1_g4=S2_U_R1_sketch.Line(point1=(72.46,233.85),point2=(56.95,255.6))
S2_U_R1_g5=S2_U_R1_sketch.Line(point1=(56.95,255.6),point2=(25,255.6))
S2_U_R1_g6=S2_U_R1_sketch.Line(point1=(25,255.6),point2=(25,217))
S2_U_R1_sketch.FilletByRadius(radius=2,curve1=S2_U_R1_g1, nearPoint1=(25,217),curve2=S2_U_R1_g2, nearPoint2=(74.68,219.85))
S2_U_R1_sketch.FilletByRadius(radius=0.5,curve1=S2_U_R1_g2, nearPoint1=(58.52,217),curve2=S2_U_R1_g3, nearPoint2=(72.46,233.85))
S2_U_R1_sketch.FilletByRadius(radius=4,curve1=S2_U_R1_g3, nearPoint1=(74.68,219.85),curve2=S2_U_R1_g4, nearPoint2=(56.95,255.6))
S2_U_R1_sketch.FilletByRadius(radius=1,curve1=S2_U_R1_g4, nearPoint1=(72.46,233.85),curve2=S2_U_R1_g5, nearPoint2=(25,255.6))
S2_U_R1=Hutprofil.Part(name='S2_U_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_U_R1.AnalyticRigidSurfRevolve(sketch=S2_U_R1_sketch)
aS2_U_R1 = aHutprofil.Instance(name='aS2_U_R1', part=S2_U_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_U_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_U_R1', ), vector=(275 , 292.5, 400))
S2_U_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_11', sheetSize=250.0)
S2_U_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_U_R2_sketch.FixedConstraint(entity=S2_U_R2_sketch.geometry[2])
S2_U_R2_g1=S2_U_R2_sketch.Line(point1=(25,255.6),point2=(57,255.6))
S2_U_R2_g2=S2_U_R2_sketch.Line(point1=(57,255.6),point2=(57,289.6))
S2_U_R2_g3=S2_U_R2_sketch.Line(point1=(57,289.6),point2=(25,289.6))
S2_U_R2_g4=S2_U_R2_sketch.Line(point1=(25,289.6),point2=(25,255.6))
S2_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S2_U_R2_g1, nearPoint1=(25,255.6),curve2=S2_U_R2_g2, nearPoint2=(57,289.6))
S2_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S2_U_R2_g2, nearPoint1=(57,255.6),curve2=S2_U_R2_g3, nearPoint2=(25,289.6))
S2_U_R2=Hutprofil.Part(name='S2_U_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_U_R2.AnalyticRigidSurfRevolve(sketch=S2_U_R2_sketch)
aS2_U_R2 = aHutprofil.Instance(name='aS2_U_R2', part=S2_U_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_U_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_U_R2', ), vector=(275 , 292.5, 400))
S2_U_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_12', sheetSize=250.0)
S2_U_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_U_R3_sketch.FixedConstraint(entity=S2_U_R3_sketch.geometry[2])
S2_U_R3_g1=S2_U_R3_sketch.Line(point1=(25,289.6),point2=(57.18,289.6))
S2_U_R3_g2=S2_U_R3_sketch.Line(point1=(57.18,289.6),point2=(69.19,301.4))
S2_U_R3_g3=S2_U_R3_sketch.Line(point1=(69.19,301.4),point2=(70.58,310.18))
S2_U_R3_g4=S2_U_R3_sketch.Line(point1=(70.58,310.18),point2=(54.61,313))
S2_U_R3_g5=S2_U_R3_sketch.Line(point1=(54.61,313),point2=(25,313))
S2_U_R3_g6=S2_U_R3_sketch.Line(point1=(25,313),point2=(25,289.6))
S2_U_R3_sketch.FilletByRadius(radius=1,curve1=S2_U_R3_g1, nearPoint1=(25,289.6),curve2=S2_U_R3_g2, nearPoint2=(69.19,301.4))
S2_U_R3_sketch.FilletByRadius(radius=3.5,curve1=S2_U_R3_g2, nearPoint1=(57.18,289.6),curve2=S2_U_R3_g3, nearPoint2=(70.58,310.18))
S2_U_R3_sketch.FilletByRadius(radius=0.5,curve1=S2_U_R3_g3, nearPoint1=(69.19,301.4),curve2=S2_U_R3_g4, nearPoint2=(54.61,313))
S2_U_R3_sketch.FilletByRadius(radius=5,curve1=S2_U_R3_g4, nearPoint1=(70.58,310.18),curve2=S2_U_R3_g5, nearPoint2=(25,313))
S2_U_R3=Hutprofil.Part(name='S2_U_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_U_R3.AnalyticRigidSurfRevolve(sketch=S2_U_R3_sketch)
aS2_U_R3 = aHutprofil.Instance(name='aS2_U_R3', part=S2_U_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_U_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_U_R3', ), vector=(275 , 292.5, 400))
S2_O_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_13', sheetSize=250.0)
S2_O_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_O_R1_sketch.FixedConstraint(entity=S2_O_R1_sketch.geometry[2])
S2_O_R1_g1=S2_O_R1_sketch.Line(point1=(25,205.1),point2=(80,205.1))
S2_O_R1_g2=S2_O_R1_sketch.Line(point1=(80,205.1),point2=(80,216.66))
S2_O_R1_g3=S2_O_R1_sketch.Line(point1=(80,216.66),point2=(60.5,220.1))
S2_O_R1_g4=S2_O_R1_sketch.Line(point1=(60.5,220.1),point2=(25,220.1))
S2_O_R1_g5=S2_O_R1_sketch.Line(point1=(25,220.1),point2=(25,205.1))
S2_O_R1_sketch.FilletByRadius(radius=0.5,curve1=S2_O_R1_g1, nearPoint1=(25,205.1),curve2=S2_O_R1_g2, nearPoint2=(80,216.66))
S2_O_R1_sketch.FilletByRadius(radius=1,curve1=S2_O_R1_g2, nearPoint1=(80,205.1),curve2=S2_O_R1_g3, nearPoint2=(60.5,220.1))
S2_O_R1_sketch.FilletByRadius(radius=1,curve1=S2_O_R1_g3, nearPoint1=(80,216.66),curve2=S2_O_R1_g4, nearPoint2=(25,220.1))
S2_O_R1=Hutprofil.Part(name='S2_O_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_O_R1.AnalyticRigidSurfRevolve(sketch=S2_O_R1_sketch)
aS2_O_R1 = aHutprofil.Instance(name='aS2_O_R1', part=S2_O_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_O_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_O_R1', ), vector=(275, 430.5, 400))
S2_O_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_14', sheetSize=250.0)
S2_O_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_O_R2_sketch.FixedConstraint(entity=S2_O_R2_sketch.geometry[2])
S2_O_R2_g1=S2_O_R2_sketch.Line(point1=(25,220.1),point2=(61.26,220.1))
S2_O_R2_g2=S2_O_R2_sketch.Line(point1=(61.26,220.1),point2=(66.76,251.3))
S2_O_R2_g3=S2_O_R2_sketch.Line(point1=(66.76,251.3),point2=(25,251.3))
S2_O_R2_g4=S2_O_R2_sketch.Line(point1=(25,251.3),point2=(25,220.1))
S2_O_R2_sketch.FilletByRadius(radius=0.5,curve1=S2_O_R2_g1, nearPoint1=(25,220.1),curve2=S2_O_R2_g2, nearPoint2=(66.76,251.3))
S2_O_R2_sketch.FilletByRadius(radius=1,curve1=S2_O_R2_g2, nearPoint1=(61.26,220.1),curve2=S2_O_R2_g3, nearPoint2=(25,251.3))
S2_O_R2=Hutprofil.Part(name='S2_O_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_O_R2.AnalyticRigidSurfRevolve(sketch=S2_O_R2_sketch)
aS2_O_R2 = aHutprofil.Instance(name='aS2_O_R2', part=S2_O_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_O_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_O_R2', ), vector=(275, 430.5, 400))
S2_O_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_15', sheetSize=250.0)
S2_O_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_O_R3_sketch.FixedConstraint(entity=S2_O_R3_sketch.geometry[2])
S2_O_R3_g1=S2_O_R3_sketch.Line(point1=(25,251.3),point2=(75.47,251.3))
S2_O_R3_g2=S2_O_R3_sketch.Line(point1=(75.47,251.3),point2=(79.5,256.27))
S2_O_R3_g3=S2_O_R3_sketch.Line(point1=(79.5,256.27),point2=(79.5,288.69))
S2_O_R3_g4=S2_O_R3_sketch.Line(point1=(79.5,288.69),point2=(72.43,295))
S2_O_R3_g5=S2_O_R3_sketch.Line(point1=(72.43,295),point2=(25,295))
S2_O_R3_g6=S2_O_R3_sketch.Line(point1=(25,295),point2=(25,251.3))
S2_O_R3_sketch.FilletByRadius(radius=1,curve1=S2_O_R3_g1, nearPoint1=(25,251.3),curve2=S2_O_R3_g2, nearPoint2=(79.5,256.27))
S2_O_R3_sketch.FilletByRadius(radius=3,curve1=S2_O_R3_g2, nearPoint1=(75.47,251.3),curve2=S2_O_R3_g3, nearPoint2=(79.5,288.69))
S2_O_R3_sketch.FilletByRadius(radius=3,curve1=S2_O_R3_g3, nearPoint1=(79.5,256.27),curve2=S2_O_R3_g4, nearPoint2=(72.43,295))
S2_O_R3_sketch.FilletByRadius(radius=10,curve1=S2_O_R3_g4, nearPoint1=(79.5,288.69),curve2=S2_O_R3_g5, nearPoint2=(25,295))
S2_O_R3=Hutprofil.Part(name='S2_O_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_O_R3.AnalyticRigidSurfRevolve(sketch=S2_O_R3_sketch)
aS2_O_R3 = aHutprofil.Instance(name='aS2_O_R3', part=S2_O_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_O_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_O_R3', ), vector=(275, 430.5, 400))
S2_O_R4_sketch=Hutprofil.ConstrainedSketch(name='Sketch_16', sheetSize=250.0)
S2_O_R4_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_O_R4_sketch.FixedConstraint(entity=S2_O_R4_sketch.geometry[2])
S2_O_R4_g1=S2_O_R4_sketch.Line(point1=(25,295),point2=(68.14,295))
S2_O_R4_g2=S2_O_R4_sketch.Line(point1=(68.14,295),point2=(65.5,310))
S2_O_R4_g3=S2_O_R4_sketch.Line(point1=(65.5,310),point2=(25,310))
S2_O_R4_g4=S2_O_R4_sketch.Line(point1=(25,310),point2=(25,295))
S2_O_R4_sketch.FilletByRadius(radius=0.5,curve1=S2_O_R4_g1, nearPoint1=(25,295),curve2=S2_O_R4_g2, nearPoint2=(65.5,310))
S2_O_R4_sketch.FilletByRadius(radius=0.5,curve1=S2_O_R4_g2, nearPoint1=(68.14,295),curve2=S2_O_R4_g3, nearPoint2=(25,310))
S2_O_R4=Hutprofil.Part(name='S2_O_R4',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_O_R4.AnalyticRigidSurfRevolve(sketch=S2_O_R4_sketch)
aS2_O_R4 = aHutprofil.Instance(name='aS2_O_R4', part=S2_O_R4,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_O_R4', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_O_R4', ), vector=(275, 430.5, 400))
S2_O_R5_sketch=Hutprofil.ConstrainedSketch(name='Sketch_17', sheetSize=250.0)
S2_O_R5_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S2_O_R5_sketch.FixedConstraint(entity=S2_O_R5_sketch.geometry[2])
S2_O_R5_g1=S2_O_R5_sketch.Line(point1=(25,310),point2=(65,310))
S2_O_R5_g2=S2_O_R5_sketch.Line(point1=(65,310),point2=(90,314.41))
S2_O_R5_g3=S2_O_R5_sketch.Line(point1=(90,314.41),point2=(90,330))
S2_O_R5_g4=S2_O_R5_sketch.Line(point1=(90,330),point2=(25,330))
S2_O_R5_g5=S2_O_R5_sketch.Line(point1=(25,330),point2=(25,310))
S2_O_R5_sketch.FilletByRadius(radius=0.5,curve1=S2_O_R5_g1, nearPoint1=(25,310),curve2=S2_O_R5_g2, nearPoint2=(90,314.41))
S2_O_R5_sketch.FilletByRadius(radius=0.5,curve1=S2_O_R5_g2, nearPoint1=(65,310),curve2=S2_O_R5_g3, nearPoint2=(90,330))
S2_O_R5_sketch.FilletByRadius(radius=0.5,curve1=S2_O_R5_g3, nearPoint1=(90,314.41),curve2=S2_O_R5_g4, nearPoint2=(25,330))
S2_O_R5=Hutprofil.Part(name='S2_O_R5',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S2_O_R5.AnalyticRigidSurfRevolve(sketch=S2_O_R5_sketch)
aS2_O_R5 = aHutprofil.Instance(name='aS2_O_R5', part=S2_O_R5,dependent=ON)
aHutprofil.rotate(instanceList=('aS2_O_R5', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS2_O_R5', ), vector=(275, 430.5, 400))
S3_U_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_18', sheetSize=250.0)
S3_U_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_U_R1_sketch.FixedConstraint(entity=S3_U_R1_sketch.geometry[2])
S3_U_R1_g1=S3_U_R1_sketch.Line(point1=(25,223.5),point2=(67.31,223.5))
S3_U_R1_g2=S3_U_R1_sketch.Line(point1=(67.31,223.5),point2=(78.89,224.51))
S3_U_R1_g3=S3_U_R1_sketch.Line(point1=(78.89,224.51),point2=(77.91,238.54))
S3_U_R1_g4=S3_U_R1_sketch.Line(point1=(77.91,238.54),point2=(56.96,255.5))
S3_U_R1_g5=S3_U_R1_sketch.Line(point1=(56.96,255.5),point2=(25,255.5))
S3_U_R1_g6=S3_U_R1_sketch.Line(point1=(25,255.5),point2=(25,223.5))
S3_U_R1_sketch.FilletByRadius(radius=10,curve1=S3_U_R1_g1, nearPoint1=(25,223.5),curve2=S3_U_R1_g2, nearPoint2=(78.89,224.51))
S3_U_R1_sketch.FilletByRadius(radius=0.5,curve1=S3_U_R1_g2, nearPoint1=(67.31,223.5),curve2=S3_U_R1_g3, nearPoint2=(77.91,238.54))
S3_U_R1_sketch.FilletByRadius(radius=2,curve1=S3_U_R1_g3, nearPoint1=(78.89,224.51),curve2=S3_U_R1_g4, nearPoint2=(56.96,255.5))
S3_U_R1_sketch.FilletByRadius(radius=1,curve1=S3_U_R1_g4, nearPoint1=(77.91,238.54),curve2=S3_U_R1_g5, nearPoint2=(25,255.5))
S3_U_R1=Hutprofil.Part(name='S3_U_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_U_R1.AnalyticRigidSurfRevolve(sketch=S3_U_R1_sketch)
aS3_U_R1 = aHutprofil.Instance(name='aS3_U_R1', part=S3_U_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_U_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_U_R1', ), vector=(275 , 290.5, 800))
S3_U_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_19', sheetSize=250.0)
S3_U_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_U_R2_sketch.FixedConstraint(entity=S3_U_R2_sketch.geometry[2])
S3_U_R2_g1=S3_U_R2_sketch.Line(point1=(25,255.5),point2=(57,255.5))
S3_U_R2_g2=S3_U_R2_sketch.Line(point1=(57,255.5),point2=(57,289.5))
S3_U_R2_g3=S3_U_R2_sketch.Line(point1=(57,289.5),point2=(25,289.5))
S3_U_R2_g4=S3_U_R2_sketch.Line(point1=(25,289.5),point2=(25,255.5))
S3_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S3_U_R2_g1, nearPoint1=(25,255.5),curve2=S3_U_R2_g2, nearPoint2=(57,289.5))
S3_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S3_U_R2_g2, nearPoint1=(57,255.5),curve2=S3_U_R2_g3, nearPoint2=(25,289.5))
S3_U_R2=Hutprofil.Part(name='S3_U_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_U_R2.AnalyticRigidSurfRevolve(sketch=S3_U_R2_sketch)
aS3_U_R2 = aHutprofil.Instance(name='aS3_U_R2', part=S3_U_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_U_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_U_R2', ), vector=(275 , 290.5, 800))
S3_U_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_20', sheetSize=250.0)
S3_U_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_U_R3_sketch.FixedConstraint(entity=S3_U_R3_sketch.geometry[2])
S3_U_R3_g1=S3_U_R3_sketch.Line(point1=(25,289.5),point2=(56.72,289.5))
S3_U_R3_g2=S3_U_R3_sketch.Line(point1=(56.72,289.5),point2=(72.43,297.5))
S3_U_R3_g3=S3_U_R3_sketch.Line(point1=(72.43,297.5),point2=(73.13,306.4))
S3_U_R3_g4=S3_U_R3_sketch.Line(point1=(73.13,306.4),point2=(54.85,308))
S3_U_R3_g5=S3_U_R3_sketch.Line(point1=(54.85,308),point2=(25,308))
S3_U_R3_g6=S3_U_R3_sketch.Line(point1=(25,308),point2=(25,289.5))
S3_U_R3_sketch.FilletByRadius(radius=2,curve1=S3_U_R3_g1, nearPoint1=(25,289.5),curve2=S3_U_R3_g2, nearPoint2=(72.43,297.5))
S3_U_R3_sketch.FilletByRadius(radius=2,curve1=S3_U_R3_g2, nearPoint1=(56.72,289.5),curve2=S3_U_R3_g3, nearPoint2=(73.13,306.4))
S3_U_R3_sketch.FilletByRadius(radius=0.5,curve1=S3_U_R3_g3, nearPoint1=(72.43,297.5),curve2=S3_U_R3_g4, nearPoint2=(54.85,308))
S3_U_R3_sketch.FilletByRadius(radius=5,curve1=S3_U_R3_g4, nearPoint1=(73.13,306.4),curve2=S3_U_R3_g5, nearPoint2=(25,308))
S3_U_R3=Hutprofil.Part(name='S3_U_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_U_R3.AnalyticRigidSurfRevolve(sketch=S3_U_R3_sketch)
aS3_U_R3 = aHutprofil.Instance(name='aS3_U_R3', part=S3_U_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_U_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_U_R3', ), vector=(275 , 290.5, 800))
S3_O_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_21', sheetSize=250.0)
S3_O_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_O_R1_sketch.FixedConstraint(entity=S3_O_R1_sketch.geometry[2])
S3_O_R1_g1=S3_O_R1_sketch.Line(point1=(25,190),point2=(85,190))
S3_O_R1_g2=S3_O_R1_sketch.Line(point1=(85,190),point2=(85,217.59))
S3_O_R1_g3=S3_O_R1_sketch.Line(point1=(85,217.59),point2=(71.44,223.2))
S3_O_R1_g4=S3_O_R1_sketch.Line(point1=(71.44,223.2),point2=(56.6,224.5))
S3_O_R1_g5=S3_O_R1_sketch.Line(point1=(56.6,224.5),point2=(25,224.5))
S3_O_R1_g6=S3_O_R1_sketch.Line(point1=(25,224.5),point2=(25,190))
S3_O_R1_sketch.FilletByRadius(radius=1,curve1=S3_O_R1_g1, nearPoint1=(25,190),curve2=S3_O_R1_g2, nearPoint2=(85,217.59))
S3_O_R1_sketch.FilletByRadius(radius=2,curve1=S3_O_R1_g2, nearPoint1=(85,190),curve2=S3_O_R1_g3, nearPoint2=(71.44,223.2))
S3_O_R1_sketch.FilletByRadius(radius=30,curve1=S3_O_R1_g3, nearPoint1=(85,217.59),curve2=S3_O_R1_g4, nearPoint2=(56.6,224.5))
S3_O_R1_sketch.FilletByRadius(radius=5,curve1=S3_O_R1_g4, nearPoint1=(71.44,223.2),curve2=S3_O_R1_g5, nearPoint2=(25,224.5))
S3_O_R1=Hutprofil.Part(name='S3_O_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_O_R1.AnalyticRigidSurfRevolve(sketch=S3_O_R1_sketch)
aS3_O_R1 = aHutprofil.Instance(name='aS3_O_R1', part=S3_O_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_O_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_O_R1', ), vector=(275, 428.5, 800))
S3_O_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_22', sheetSize=250.0)
S3_O_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_O_R2_sketch.FixedConstraint(entity=S3_O_R2_sketch.geometry[2])
S3_O_R2_g1=S3_O_R2_sketch.Line(point1=(25,224.5),point2=(57.25,224.5))
S3_O_R2_g2=S3_O_R2_sketch.Line(point1=(57.25,224.5),point2=(58.56,239.5))
S3_O_R2_g3=S3_O_R2_sketch.Line(point1=(58.56,239.5),point2=(25,239.5))
S3_O_R2_g4=S3_O_R2_sketch.Line(point1=(25,239.5),point2=(25,224.5))
S3_O_R2_sketch.FilletByRadius(radius=0.5,curve1=S3_O_R2_g1, nearPoint1=(25,224.5),curve2=S3_O_R2_g2, nearPoint2=(58.56,239.5))
S3_O_R2_sketch.FilletByRadius(radius=0.5,curve1=S3_O_R2_g2, nearPoint1=(57.25,224.5),curve2=S3_O_R2_g3, nearPoint2=(25,239.5))
S3_O_R2=Hutprofil.Part(name='S3_O_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_O_R2.AnalyticRigidSurfRevolve(sketch=S3_O_R2_sketch)
aS3_O_R2 = aHutprofil.Instance(name='aS3_O_R2', part=S3_O_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_O_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_O_R2', ), vector=(275, 428.5, 800))
S3_O_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_23', sheetSize=250.0)
S3_O_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_O_R3_sketch.FixedConstraint(entity=S3_O_R3_sketch.geometry[2])
S3_O_R3_g1=S3_O_R3_sketch.Line(point1=(25,239.5),point2=(58.55,239.5))
S3_O_R3_g2=S3_O_R3_sketch.Line(point1=(58.55,239.5),point2=(79.5,256.46))
S3_O_R3_g3=S3_O_R3_sketch.Line(point1=(79.5,256.46),point2=(79.5,288.58))
S3_O_R3_g4=S3_O_R3_sketch.Line(point1=(79.5,288.58),point2=(64.16,296.4))
S3_O_R3_g5=S3_O_R3_sketch.Line(point1=(64.16,296.4),point2=(25,296.4))
S3_O_R3_g6=S3_O_R3_sketch.Line(point1=(25,296.4),point2=(25,239.5))
S3_O_R3_sketch.FilletByRadius(radius=4,curve1=S3_O_R3_g1, nearPoint1=(25,239.5),curve2=S3_O_R3_g2, nearPoint2=(79.5,256.46))
S3_O_R3_sketch.FilletByRadius(radius=2,curve1=S3_O_R3_g2, nearPoint1=(58.55,239.5),curve2=S3_O_R3_g3, nearPoint2=(79.5,288.58))
S3_O_R3_sketch.FilletByRadius(radius=2,curve1=S3_O_R3_g3, nearPoint1=(79.5,256.46),curve2=S3_O_R3_g4, nearPoint2=(64.16,296.4))
S3_O_R3_sketch.FilletByRadius(radius=4,curve1=S3_O_R3_g4, nearPoint1=(79.5,288.58),curve2=S3_O_R3_g5, nearPoint2=(25,296.4))
S3_O_R3=Hutprofil.Part(name='S3_O_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_O_R3.AnalyticRigidSurfRevolve(sketch=S3_O_R3_sketch)
aS3_O_R3 = aHutprofil.Instance(name='aS3_O_R3', part=S3_O_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_O_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_O_R3', ), vector=(275, 428.5, 800))
S3_O_R4_sketch=Hutprofil.ConstrainedSketch(name='Sketch_24', sheetSize=250.0)
S3_O_R4_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_O_R4_sketch.FixedConstraint(entity=S3_O_R4_sketch.geometry[2])
S3_O_R4_g1=S3_O_R4_sketch.Line(point1=(25,296.4),point2=(64.07,296.4))
S3_O_R4_g2=S3_O_R4_sketch.Line(point1=(64.07,296.4),point2=(63.2,306.4))
S3_O_R4_g3=S3_O_R4_sketch.Line(point1=(63.2,306.4),point2=(25,306.4))
S3_O_R4_g4=S3_O_R4_sketch.Line(point1=(25,306.4),point2=(25,296.4))
S3_O_R4_sketch.FilletByRadius(radius=0.5,curve1=S3_O_R4_g1, nearPoint1=(25,296.4),curve2=S3_O_R4_g2, nearPoint2=(63.2,306.4))
S3_O_R4_sketch.FilletByRadius(radius=0.5,curve1=S3_O_R4_g2, nearPoint1=(64.07,296.4),curve2=S3_O_R4_g3, nearPoint2=(25,306.4))
S3_O_R4=Hutprofil.Part(name='S3_O_R4',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_O_R4.AnalyticRigidSurfRevolve(sketch=S3_O_R4_sketch)
aS3_O_R4 = aHutprofil.Instance(name='aS3_O_R4', part=S3_O_R4,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_O_R4', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_O_R4', ), vector=(275, 428.5, 800))
S3_O_R5_sketch=Hutprofil.ConstrainedSketch(name='Sketch_25', sheetSize=250.0)
S3_O_R5_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S3_O_R5_sketch.FixedConstraint(entity=S3_O_R5_sketch.geometry[2])
S3_O_R5_g1=S3_O_R5_sketch.Line(point1=(25,306.4),point2=(62.79,306.4))
S3_O_R5_g2=S3_O_R5_sketch.Line(point1=(62.79,306.4),point2=(75.11,307.48))
S3_O_R5_g3=S3_O_R5_sketch.Line(point1=(75.11,307.48),point2=(85,311.28))
S3_O_R5_g4=S3_O_R5_sketch.Line(point1=(85,311.28),point2=(85,340))
S3_O_R5_g5=S3_O_R5_sketch.Line(point1=(85,340),point2=(25,340))
S3_O_R5_g6=S3_O_R5_sketch.Line(point1=(25,340),point2=(25,306.4))
S3_O_R5_sketch.FilletByRadius(radius=5,curve1=S3_O_R5_g1, nearPoint1=(25,306.4),curve2=S3_O_R5_g2, nearPoint2=(75.11,307.48))
S3_O_R5_sketch.FilletByRadius(radius=30,curve1=S3_O_R5_g2, nearPoint1=(62.79,306.4),curve2=S3_O_R5_g3, nearPoint2=(85,311.28))
S3_O_R5_sketch.FilletByRadius(radius=2,curve1=S3_O_R5_g3, nearPoint1=(75.11,307.48),curve2=S3_O_R5_g4, nearPoint2=(85,340))
S3_O_R5_sketch.FilletByRadius(radius=1,curve1=S3_O_R5_g4, nearPoint1=(85,311.28),curve2=S3_O_R5_g5, nearPoint2=(25,340))
S3_O_R5=Hutprofil.Part(name='S3_O_R5',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S3_O_R5.AnalyticRigidSurfRevolve(sketch=S3_O_R5_sketch)
aS3_O_R5 = aHutprofil.Instance(name='aS3_O_R5', part=S3_O_R5,dependent=ON)
aHutprofil.rotate(instanceList=('aS3_O_R5', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS3_O_R5', ), vector=(275, 428.5, 800))
S4_U_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_26', sheetSize=250.0)
S4_U_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S4_U_R1_sketch.FixedConstraint(entity=S4_U_R1_sketch.geometry[2])
S4_U_R1_g1=S4_U_R1_sketch.Line(point1=(25,220),point2=(80.33,220))
S4_U_R1_g2=S4_U_R1_sketch.Line(point1=(80.33,220),point2=(80.72,242.5))
S4_U_R1_g3=S4_U_R1_sketch.Line(point1=(80.72,242.5),point2=(55.86,256))
S4_U_R1_g4=S4_U_R1_sketch.Line(point1=(55.86,256),point2=(25,256))
S4_U_R1_g5=S4_U_R1_sketch.Line(point1=(25,256),point2=(25,220))
S4_U_R1_sketch.FilletByRadius(radius=0.5,curve1=S4_U_R1_g1, nearPoint1=(25,220),curve2=S4_U_R1_g2, nearPoint2=(80.72,242.5))
S4_U_R1_sketch.FilletByRadius(radius=1.5,curve1=S4_U_R1_g2, nearPoint1=(80.33,220),curve2=S4_U_R1_g3, nearPoint2=(55.86,256))
S4_U_R1_sketch.FilletByRadius(radius=2,curve1=S4_U_R1_g3, nearPoint1=(80.72,242.5),curve2=S4_U_R1_g4, nearPoint2=(25,256))
S4_U_R1=Hutprofil.Part(name='S4_U_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S4_U_R1.AnalyticRigidSurfRevolve(sketch=S4_U_R1_sketch)
aS4_U_R1 = aHutprofil.Instance(name='aS4_U_R1', part=S4_U_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS4_U_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS4_U_R1', ), vector=(275 , 290.5, 1200))
S4_U_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_27', sheetSize=250.0)
S4_U_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S4_U_R2_sketch.FixedConstraint(entity=S4_U_R2_sketch.geometry[2])
S4_U_R2_g1=S4_U_R2_sketch.Line(point1=(25,256),point2=(57,256))
S4_U_R2_g2=S4_U_R2_sketch.Line(point1=(57,256),point2=(57,289))
S4_U_R2_g3=S4_U_R2_sketch.Line(point1=(57,289),point2=(25,289))
S4_U_R2_g4=S4_U_R2_sketch.Line(point1=(25,289),point2=(25,256))
S4_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S4_U_R2_g1, nearPoint1=(25,256),curve2=S4_U_R2_g2, nearPoint2=(57,289))
S4_U_R2_sketch.FilletByRadius(radius=0.5,curve1=S4_U_R2_g2, nearPoint1=(57,256),curve2=S4_U_R2_g3, nearPoint2=(25,289))
S4_U_R2=Hutprofil.Part(name='S4_U_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S4_U_R2.AnalyticRigidSurfRevolve(sketch=S4_U_R2_sketch)
aS4_U_R2 = aHutprofil.Instance(name='aS4_U_R2', part=S4_U_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS4_U_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS4_U_R2', ), vector=(275 , 290.5, 1200))
S4_U_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_28', sheetSize=250.0)
S4_U_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S4_U_R3_sketch.FixedConstraint(entity=S4_U_R3_sketch.geometry[2])
S4_U_R3_g1=S4_U_R3_sketch.Line(point1=(25,289),point2=(53.53,289))
S4_U_R3_g2=S4_U_R3_sketch.Line(point1=(53.53,289),point2=(74.08,293.93))
S4_U_R3_g3=S4_U_R3_sketch.Line(point1=(74.08,293.93),point2=(73.8,310))
S4_U_R3_g4=S4_U_R3_sketch.Line(point1=(73.8,310),point2=(25,310))
S4_U_R3_g5=S4_U_R3_sketch.Line(point1=(25,310),point2=(25,289))
S4_U_R3_sketch.FilletByRadius(radius=2,curve1=S4_U_R3_g1, nearPoint1=(25,289),curve2=S4_U_R3_g2, nearPoint2=(74.08,293.93))
S4_U_R3_sketch.FilletByRadius(radius=1.5,curve1=S4_U_R3_g2, nearPoint1=(53.53,289),curve2=S4_U_R3_g3, nearPoint2=(73.8,310))
S4_U_R3_sketch.FilletByRadius(radius=0.5,curve1=S4_U_R3_g3, nearPoint1=(74.08,293.93),curve2=S4_U_R3_g4, nearPoint2=(25,310))
S4_U_R3=Hutprofil.Part(name='S4_U_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S4_U_R3.AnalyticRigidSurfRevolve(sketch=S4_U_R3_sketch)
aS4_U_R3 = aHutprofil.Instance(name='aS4_U_R3', part=S4_U_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS4_U_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS4_U_R3', ), vector=(275 , 290.5, 1200))
S4_O_R1_sketch=Hutprofil.ConstrainedSketch(name='Sketch_29', sheetSize=250.0)
S4_O_R1_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S4_O_R1_sketch.FixedConstraint(entity=S4_O_R1_sketch.geometry[2])
S4_O_R1_g1=S4_O_R1_sketch.Line(point1=(25,205),point2=(55.75,205))
S4_O_R1_g2=S4_O_R1_sketch.Line(point1=(55.75,205),point2=(55.75,243.9))
S4_O_R1_g3=S4_O_R1_sketch.Line(point1=(55.75,243.9),point2=(25,243.9))
S4_O_R1_g4=S4_O_R1_sketch.Line(point1=(25,243.9),point2=(25,205))
S4_O_R1_sketch.FilletByRadius(radius=0.5,curve1=S4_O_R1_g1, nearPoint1=(25,205),curve2=S4_O_R1_g2, nearPoint2=(55.75,243.9))
S4_O_R1_sketch.FilletByRadius(radius=0.5,curve1=S4_O_R1_g2, nearPoint1=(55.75,205),curve2=S4_O_R1_g3, nearPoint2=(25,243.9))
S4_O_R1=Hutprofil.Part(name='S4_O_R1',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S4_O_R1.AnalyticRigidSurfRevolve(sketch=S4_O_R1_sketch)
aS4_O_R1 = aHutprofil.Instance(name='aS4_O_R1', part=S4_O_R1,dependent=ON)
aHutprofil.rotate(instanceList=('aS4_O_R1', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS4_O_R1', ), vector=(275, 428.5, 1200))
S4_O_R2_sketch=Hutprofil.ConstrainedSketch(name='Sketch_30', sheetSize=250.0)
S4_O_R2_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S4_O_R2_sketch.FixedConstraint(entity=S4_O_R2_sketch.geometry[2])
S4_O_R2_g1=S4_O_R2_sketch.Line(point1=(25,243.9),point2=(56.26,243.9))
S4_O_R2_g2=S4_O_R2_sketch.Line(point1=(56.26,243.9),point2=(79.5,256.52))
S4_O_R2_g3=S4_O_R2_sketch.Line(point1=(79.5,256.52),point2=(79.5,288.53))
S4_O_R2_g4=S4_O_R2_sketch.Line(point1=(79.5,288.53),point2=(60.58,292.9))
S4_O_R2_g5=S4_O_R2_sketch.Line(point1=(60.58,292.9),point2=(25,292.9))
S4_O_R2_g6=S4_O_R2_sketch.Line(point1=(25,292.9),point2=(25,243.9))
S4_O_R2_sketch.FilletByRadius(radius=3,curve1=S4_O_R2_g1, nearPoint1=(25,243.9),curve2=S4_O_R2_g2, nearPoint2=(79.5,256.52))
S4_O_R2_sketch.FilletByRadius(radius=1.5,curve1=S4_O_R2_g2, nearPoint1=(56.26,243.9),curve2=S4_O_R2_g3, nearPoint2=(79.5,288.53))
S4_O_R2_sketch.FilletByRadius(radius=1.5,curve1=S4_O_R2_g3, nearPoint1=(79.5,256.52),curve2=S4_O_R2_g4, nearPoint2=(60.58,292.9))
S4_O_R2_sketch.FilletByRadius(radius=3,curve1=S4_O_R2_g4, nearPoint1=(79.5,288.53),curve2=S4_O_R2_g5, nearPoint2=(25,292.9))
S4_O_R2=Hutprofil.Part(name='S4_O_R2',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S4_O_R2.AnalyticRigidSurfRevolve(sketch=S4_O_R2_sketch)
aS4_O_R2 = aHutprofil.Instance(name='aS4_O_R2', part=S4_O_R2,dependent=ON)
aHutprofil.rotate(instanceList=('aS4_O_R2', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS4_O_R2', ), vector=(275, 428.5, 1200))
S4_O_R3_sketch=Hutprofil.ConstrainedSketch(name='Sketch_31', sheetSize=250.0)
S4_O_R3_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
S4_O_R3_sketch.FixedConstraint(entity=S4_O_R3_sketch.geometry[2])
S4_O_R3_g1=S4_O_R3_sketch.Line(point1=(25,292.9),point2=(62.4,292.9))
S4_O_R3_g2=S4_O_R3_sketch.Line(point1=(62.4,292.9),point2=(62.4,320.4))
S4_O_R3_g3=S4_O_R3_sketch.Line(point1=(62.4,320.4),point2=(25,320.4))
S4_O_R3_g4=S4_O_R3_sketch.Line(point1=(25,320.4),point2=(25,292.9))
S4_O_R3_sketch.FilletByRadius(radius=1,curve1=S4_O_R3_g1, nearPoint1=(25,292.9),curve2=S4_O_R3_g2, nearPoint2=(62.4,320.4))
S4_O_R3_sketch.FilletByRadius(radius=2,curve1=S4_O_R3_g2, nearPoint1=(62.4,292.9),curve2=S4_O_R3_g3, nearPoint2=(25,320.4))
S4_O_R3=Hutprofil.Part(name='S4_O_R3',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
S4_O_R3.AnalyticRigidSurfRevolve(sketch=S4_O_R3_sketch)
aS4_O_R3 = aHutprofil.Instance(name='aS4_O_R3', part=S4_O_R3,dependent=ON)
aHutprofil.rotate(instanceList=('aS4_O_R3', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aS4_O_R3', ), vector=(275, 428.5, 1200))
#
#Blech_sketch=Hutprofil.ConstrainedSketch(name='Sketch_32', sheetSize=250.0)
#Blech_sketch.rectangle(point1=(0.0,0.0), point2=(100, 1.5))
#Blech=Hutprofil.Part(name='Blech', dimensionality=THREE_D,type=DEFORMABLE_BODY)
#Blech.BaseSolidExtrude(sketch=Blech_sketch, depth=600)
#kante_chamfer1=Blech.edges.getClosest(coordinates=((0,0.75,600),))
#kante_chamfer_ind1=kante_chamfer1.values()[0][0].index
#Blech.Chamfer(length=10,edgeList=(Blech.edges[kante_chamfer_ind1], ))
#kante_chamfer2=Blech.edges.getClosest(coordinates=((100,0.75,600),))
#kante_chamfer_ind2=kante_chamfer2.values()[0][0].index
#Blech.Chamfer(length=10,edgeList=(Blech.edges[kante_chamfer_ind2], ))
#aBlech = aHutprofil.Instance(name='aBlech', part=Blech,dependent=ON)
#aHutprofil.translate(instanceList=('aBlech', ), vector=(490, 351.5, -630))
#F_Blech=aBlech.faces
#F_Blech_sym=F_Blech.findAt(coordinates=((540,352.25,-330,),))
#RF_Blech_sym=regionToolset.Region(faces=F_Blech_sym)
#F_Blech_OW=F_Blech.findAt(coordinates=((539,353,-330,),))
#RF_Blech_OW=regionToolset.Region(side1Faces=F_Blech_OW)
#F_Blech_UW=F_Blech.findAt(coordinates=((539,351.5,-330,),))
#RF_Blech_UW=regionToolset.Region(side1Faces=F_Blech_UW)
#
FS_OW_sketch=Hutprofil.ConstrainedSketch(name='Sketch_32', sheetSize=250.0)
FS_OW_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
FS_OW_sketch.FixedConstraint(entity=FS_OW_sketch.geometry[2])
FS_OW_g1=FS_OW_sketch.Line(point1=(10,0),point2=(100,0))
FS_OW_g2=FS_OW_sketch.Line(point1=(100,0),point2=(100,110))
FS_OW_g3=FS_OW_sketch.Line(point1=(100,110),point2=(10,110))
FS_OW_g4=FS_OW_sketch.Line(point1=(10,110),point2=(10,0))
FS_OW=Hutprofil.Part(name='FS_OW',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
FS_OW.AnalyticRigidSurfRevolve(sketch=FS_OW_sketch)
aFS_OW = aHutprofil.Instance(name='aFS_OW', part=FS_OW,dependent=ON)
aHutprofil.rotate(instanceList=('aFS_OW', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aFS_OW', ), vector=(485 , 453, -300))
F_FS_OW=aFS_OW.faces
RF_FS_OW=regionToolset.Region(side1Faces=F_FS_OW)
RP_FS_OW=aHutprofil.ReferencePoint(point=(540, 453, -300))
RRP_FS_OW=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_FS_OW.id],))
RBE_FS_OW=Hutprofil.RigidBody(name='RBE_FS_OW', refPointRegion=RRP_FS_OW,surfaceRegion=RF_FS_OW)
FS_UW_sketch=Hutprofil.ConstrainedSketch(name='Sketch_33', sheetSize=250.0)
FS_UW_sketch.ConstructionLine(point1=(0.0,-100.0), point2=(0.0, 100.0))
FS_UW_sketch.FixedConstraint(entity=FS_UW_sketch.geometry[2])
FS_UW_g1=FS_UW_sketch.Line(point1=(10,0),point2=(100,0))
FS_UW_g2=FS_UW_sketch.Line(point1=(100,0),point2=(100,110))
FS_UW_g3=FS_UW_sketch.Line(point1=(100,110),point2=(10,110))
FS_UW_g4=FS_UW_sketch.Line(point1=(10,110),point2=(10,0))
FS_UW_g5=FS_UW_sketch.Line(point1=(10,0),point2=(10,0))
FS_UW=Hutprofil.Part(name='FS_UW',dimensionality=THREE_D,type=ANALYTIC_RIGID_SURFACE)
FS_UW.AnalyticRigidSurfRevolve(sketch=FS_UW_sketch)
aFS_UW = aHutprofil.Instance(name='aFS_UW', part=FS_UW,dependent=ON)
aHutprofil.rotate(instanceList=('aFS_UW', ), axisPoint=(0, 0, 0), axisDirection=(0, 0, 1), angle=-90.0)
aHutprofil.translate(instanceList=('aFS_UW', ), vector=(485 , 251.5, -300))
F_FS_UW=aFS_UW.faces
RF_FS_UW=regionToolset.Region(side1Faces=F_FS_UW)
RP_FS_UW=aHutprofil.ReferencePoint(point=(540, 251.5, -300))
RRP_FS_UW=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_FS_UW.id],))
RBE_FS_UW=Hutprofil.RigidBody(name='RBE_FS_UW', refPointRegion=RRP_FS_UW,surfaceRegion=RF_FS_UW)
F_S1_U_R1=aS1_U_R1.faces
RF_S1_U_R1=regionToolset.Region(side1Faces=F_S1_U_R1)
RP_S1_U_R1=aHutprofil.ReferencePoint(point=(510.5, 294.5, 0))
RRP_S1_U_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_U_R1.id],))
RBE_S1_U_R1=Hutprofil.RigidBody(name='RBE_S1_U_R1', refPointRegion=RRP_S1_U_R1,surfaceRegion=RF_S1_U_R1)
F_S1_U_R2=aS1_U_R2.faces
RF_S1_U_R2=regionToolset.Region(side1Faces=F_S1_U_R2)
RP_S1_U_R2=aHutprofil.ReferencePoint(point=(547.5, 294.5, 0))
RRP_S1_U_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_U_R2.id],))
RBE_S1_U_R2=Hutprofil.RigidBody(name='RBE_S1_U_R2', refPointRegion=RRP_S1_U_R2,surfaceRegion=RF_S1_U_R2)
F_S1_U_R3=aS1_U_R3.faces
RF_S1_U_R3=regionToolset.Region(side1Faces=F_S1_U_R3)
RP_S1_U_R3=aHutprofil.ReferencePoint(point=(577, 294.5, 0))
RRP_S1_U_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_U_R3.id],))
RBE_S1_U_R3=Hutprofil.RigidBody(name='RBE_S1_U_R3', refPointRegion=RRP_S1_U_R3,surfaceRegion=RF_S1_U_R3)
F_S1_O_R1=aS1_O_R1.faces
RF_S1_O_R1=regionToolset.Region(side1Faces=F_S1_O_R1)
RP_S1_O_R1=aHutprofil.ReferencePoint(point=(481, 432.5, 0))
RRP_S1_O_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_O_R1.id],))
RBE_S1_O_R1=Hutprofil.RigidBody(name='RBE_S1_O_R1', refPointRegion=RRP_S1_O_R1,surfaceRegion=RF_S1_O_R1)
F_S1_O_R2=aS1_O_R2.faces
RF_S1_O_R2=regionToolset.Region(side1Faces=F_S1_O_R2)
RP_S1_O_R2=aHutprofil.ReferencePoint(point=(502, 432.5, 0))
RRP_S1_O_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_O_R2.id],))
RBE_S1_O_R2=Hutprofil.RigidBody(name='RBE_S1_O_R2', refPointRegion=RRP_S1_O_R2,surfaceRegion=RF_S1_O_R2)
F_S1_O_R3=aS1_O_R3.faces
RF_S1_O_R3=regionToolset.Region(side1Faces=F_S1_O_R3)
RP_S1_O_R3=aHutprofil.ReferencePoint(point=(533.4, 432.5, 0))
RRP_S1_O_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_O_R3.id],))
RBE_S1_O_R3=Hutprofil.RigidBody(name='RBE_S1_O_R3', refPointRegion=RRP_S1_O_R3,surfaceRegion=RF_S1_O_R3)
F_S1_O_R4=aS1_O_R4.faces
RF_S1_O_R4=regionToolset.Region(side1Faces=F_S1_O_R4)
RP_S1_O_R4=aHutprofil.ReferencePoint(point=(561.4, 432.5, 0))
RRP_S1_O_R4=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_O_R4.id],))
RBE_S1_O_R4=Hutprofil.RigidBody(name='RBE_S1_O_R4', refPointRegion=RRP_S1_O_R4,surfaceRegion=RF_S1_O_R4)
F_S1_O_R5=aS1_O_R5.faces
RF_S1_O_R5=regionToolset.Region(side1Faces=F_S1_O_R5)
RP_S1_O_R5=aHutprofil.ReferencePoint(point=(580.65, 432.5, 0))
RRP_S1_O_R5=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_O_R5.id],))
RBE_S1_O_R5=Hutprofil.RigidBody(name='RBE_S1_O_R5', refPointRegion=RRP_S1_O_R5,surfaceRegion=RF_S1_O_R5)
F_S1_O_R6=aS1_O_R6.faces
RF_S1_O_R6=regionToolset.Region(side1Faces=F_S1_O_R6)
RP_S1_O_R6=aHutprofil.ReferencePoint(point=(596.4, 432.5, 0))
RRP_S1_O_R6=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S1_O_R6.id],))
RBE_S1_O_R6=Hutprofil.RigidBody(name='RBE_S1_O_R6', refPointRegion=RRP_S1_O_R6,surfaceRegion=RF_S1_O_R6)
F_S2_U_R1=aS2_U_R1.faces
RF_S2_U_R1=regionToolset.Region(side1Faces=F_S2_U_R1)
RP_S2_U_R1=aHutprofil.ReferencePoint(point=(511.3, 292.5, 400))
RRP_S2_U_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_U_R1.id],))
RBE_S2_U_R1=Hutprofil.RigidBody(name='RBE_S2_U_R1', refPointRegion=RRP_S2_U_R1,surfaceRegion=RF_S2_U_R1)
F_S2_U_R2=aS2_U_R2.faces
RF_S2_U_R2=regionToolset.Region(side1Faces=F_S2_U_R2)
RP_S2_U_R2=aHutprofil.ReferencePoint(point=(547.6, 292.5, 400))
RRP_S2_U_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_U_R2.id],))
RBE_S2_U_R2=Hutprofil.RigidBody(name='RBE_S2_U_R2', refPointRegion=RRP_S2_U_R2,surfaceRegion=RF_S2_U_R2)
F_S2_U_R3=aS2_U_R3.faces
RF_S2_U_R3=regionToolset.Region(side1Faces=F_S2_U_R3)
RP_S2_U_R3=aHutprofil.ReferencePoint(point=(576.3, 292.5, 400))
RRP_S2_U_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_U_R3.id],))
RBE_S2_U_R3=Hutprofil.RigidBody(name='RBE_S2_U_R3', refPointRegion=RRP_S2_U_R3,surfaceRegion=RF_S2_U_R3)
F_S2_O_R1=aS2_O_R1.faces
RF_S2_O_R1=regionToolset.Region(side1Faces=F_S2_O_R1)
RP_S2_O_R1=aHutprofil.ReferencePoint(point=(487.6, 430.5, 400))
RRP_S2_O_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_O_R1.id],))
RBE_S2_O_R1=Hutprofil.RigidBody(name='RBE_S2_O_R1', refPointRegion=RRP_S2_O_R1,surfaceRegion=RF_S2_O_R1)
F_S2_O_R2=aS2_O_R2.faces
RF_S2_O_R2=regionToolset.Region(side1Faces=F_S2_O_R2)
RP_S2_O_R2=aHutprofil.ReferencePoint(point=(510.7, 430.5, 400))
RRP_S2_O_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_O_R2.id],))
RBE_S2_O_R2=Hutprofil.RigidBody(name='RBE_S2_O_R2', refPointRegion=RRP_S2_O_R2,surfaceRegion=RF_S2_O_R2)
F_S2_O_R3=aS2_O_R3.faces
RF_S2_O_R3=regionToolset.Region(side1Faces=F_S2_O_R3)
RP_S2_O_R3=aHutprofil.ReferencePoint(point=(548.15, 430.5, 400))
RRP_S2_O_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_O_R3.id],))
RBE_S2_O_R3=Hutprofil.RigidBody(name='RBE_S2_O_R3', refPointRegion=RRP_S2_O_R3,surfaceRegion=RF_S2_O_R3)
F_S2_O_R4=aS2_O_R4.faces
RF_S2_O_R4=regionToolset.Region(side1Faces=F_S2_O_R4)
RP_S2_O_R4=aHutprofil.ReferencePoint(point=(577.5, 430.5, 400))
RRP_S2_O_R4=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_O_R4.id],))
RBE_S2_O_R4=Hutprofil.RigidBody(name='RBE_S2_O_R4', refPointRegion=RRP_S2_O_R4,surfaceRegion=RF_S2_O_R4)
F_S2_O_R5=aS2_O_R5.faces
RF_S2_O_R5=regionToolset.Region(side1Faces=F_S2_O_R5)
RP_S2_O_R5=aHutprofil.ReferencePoint(point=(595, 430.5, 400))
RRP_S2_O_R5=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S2_O_R5.id],))
RBE_S2_O_R5=Hutprofil.RigidBody(name='RBE_S2_O_R5', refPointRegion=RRP_S2_O_R5,surfaceRegion=RF_S2_O_R5)
F_S3_U_R1=aS3_U_R1.faces
RF_S3_U_R1=regionToolset.Region(side1Faces=F_S3_U_R1)
RP_S3_U_R1=aHutprofil.ReferencePoint(point=(514.5, 290.5, 800))
RRP_S3_U_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_U_R1.id],))
RBE_S3_U_R1=Hutprofil.RigidBody(name='RBE_S3_U_R1', refPointRegion=RRP_S3_U_R1,surfaceRegion=RF_S3_U_R1)
F_S3_U_R2=aS3_U_R2.faces
RF_S3_U_R2=regionToolset.Region(side1Faces=F_S3_U_R2)
RP_S3_U_R2=aHutprofil.ReferencePoint(point=(547.5, 290.5, 800))
RRP_S3_U_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_U_R2.id],))
RBE_S3_U_R2=Hutprofil.RigidBody(name='RBE_S3_U_R2', refPointRegion=RRP_S3_U_R2,surfaceRegion=RF_S3_U_R2)
F_S3_U_R3=aS3_U_R3.faces
RF_S3_U_R3=regionToolset.Region(side1Faces=F_S3_U_R3)
RP_S3_U_R3=aHutprofil.ReferencePoint(point=(573.75, 290.5, 800))
RRP_S3_U_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_U_R3.id],))
RBE_S3_U_R3=Hutprofil.RigidBody(name='RBE_S3_U_R3', refPointRegion=RRP_S3_U_R3,surfaceRegion=RF_S3_U_R3)
F_S3_O_R1=aS3_O_R1.faces
RF_S3_O_R1=regionToolset.Region(side1Faces=F_S3_O_R1)
RP_S3_O_R1=aHutprofil.ReferencePoint(point=(482.25, 428.5, 800))
RRP_S3_O_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_O_R1.id],))
RBE_S3_O_R1=Hutprofil.RigidBody(name='RBE_S3_O_R1', refPointRegion=RRP_S3_O_R1,surfaceRegion=RF_S3_O_R1)
F_S3_O_R2=aS3_O_R2.faces
RF_S3_O_R2=regionToolset.Region(side1Faces=F_S3_O_R2)
RP_S3_O_R2=aHutprofil.ReferencePoint(point=(507, 428.5, 800))
RRP_S3_O_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_O_R2.id],))
RBE_S3_O_R2=Hutprofil.RigidBody(name='RBE_S3_O_R2', refPointRegion=RRP_S3_O_R2,surfaceRegion=RF_S3_O_R2)
F_S3_O_R3=aS3_O_R3.faces
RF_S3_O_R3=regionToolset.Region(side1Faces=F_S3_O_R3)
RP_S3_O_R3=aHutprofil.ReferencePoint(point=(542.95, 428.5, 800))
RRP_S3_O_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_O_R3.id],))
RBE_S3_O_R3=Hutprofil.RigidBody(name='RBE_S3_O_R3', refPointRegion=RRP_S3_O_R3,surfaceRegion=RF_S3_O_R3)
F_S3_O_R4=aS3_O_R4.faces
RF_S3_O_R4=regionToolset.Region(side1Faces=F_S3_O_R4)
RP_S3_O_R4=aHutprofil.ReferencePoint(point=(576.4, 428.5, 800))
RRP_S3_O_R4=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_O_R4.id],))
RBE_S3_O_R4=Hutprofil.RigidBody(name='RBE_S3_O_R4', refPointRegion=RRP_S3_O_R4,surfaceRegion=RF_S3_O_R4)
F_S3_O_R5=aS3_O_R5.faces
RF_S3_O_R5=regionToolset.Region(side1Faces=F_S3_O_R5)
RP_S3_O_R5=aHutprofil.ReferencePoint(point=(598.2, 428.5, 800))
RRP_S3_O_R5=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S3_O_R5.id],))
RBE_S3_O_R5=Hutprofil.RigidBody(name='RBE_S3_O_R5', refPointRegion=RRP_S3_O_R5,surfaceRegion=RF_S3_O_R5)
F_S4_U_R1=aS4_U_R1.faces
RF_S4_U_R1=regionToolset.Region(side1Faces=F_S4_U_R1)
RP_S4_U_R1=aHutprofil.ReferencePoint(point=(513, 290.5, 1200))
RRP_S4_U_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S4_U_R1.id],))
RBE_S4_U_R1=Hutprofil.RigidBody(name='RBE_S4_U_R1', refPointRegion=RRP_S4_U_R1,surfaceRegion=RF_S4_U_R1)
F_S4_U_R2=aS4_U_R2.faces
RF_S4_U_R2=regionToolset.Region(side1Faces=F_S4_U_R2)
RP_S4_U_R2=aHutprofil.ReferencePoint(point=(547.5, 290.5, 1200))
RRP_S4_U_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S4_U_R2.id],))
RBE_S4_U_R2=Hutprofil.RigidBody(name='RBE_S4_U_R2', refPointRegion=RRP_S4_U_R2,surfaceRegion=RF_S4_U_R2)
F_S4_U_R3=aS4_U_R3.faces
RF_S4_U_R3=regionToolset.Region(side1Faces=F_S4_U_R3)
RP_S4_U_R3=aHutprofil.ReferencePoint(point=(574.5, 290.5, 1200))
RRP_S4_U_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S4_U_R3.id],))
RBE_S4_U_R3=Hutprofil.RigidBody(name='RBE_S4_U_R3', refPointRegion=RRP_S4_U_R3,surfaceRegion=RF_S4_U_R3)
F_S4_O_R1=aS4_O_R1.faces
RF_S4_O_R1=regionToolset.Region(side1Faces=F_S4_O_R1)
RP_S4_O_R1=aHutprofil.ReferencePoint(point=(499.45, 428.5, 1200))
RRP_S4_O_R1=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S4_O_R1.id],))
RBE_S4_O_R1=Hutprofil.RigidBody(name='RBE_S4_O_R1', refPointRegion=RRP_S4_O_R1,surfaceRegion=RF_S4_O_R1)
F_S4_O_R2=aS4_O_R2.faces
RF_S4_O_R2=regionToolset.Region(side1Faces=F_S4_O_R2)
RP_S4_O_R2=aHutprofil.ReferencePoint(point=(543.4, 428.5, 1200))
RRP_S4_O_R2=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S4_O_R2.id],))
RBE_S4_O_R2=Hutprofil.RigidBody(name='RBE_S4_O_R2', refPointRegion=RRP_S4_O_R2,surfaceRegion=RF_S4_O_R2)
F_S4_O_R3=aS4_O_R3.faces
RF_S4_O_R3=regionToolset.Region(side1Faces=F_S4_O_R3)
RP_S4_O_R3=aHutprofil.ReferencePoint(point=(581.65, 428.5, 1200))
RRP_S4_O_R3=regionToolset.Region(referencePoints=(aHutprofil.referencePoints[RP_S4_O_R3.id],))
RBE_S4_O_R3=Hutprofil.RigidBody(name='RBE_S4_O_R3', refPointRegion=RRP_S4_O_R3,surfaceRegion=RF_S4_O_R3)
#
#Mat = Hutprofil.Material(name='Mat')
#Mat.Density(table=((7.8e-09, ), ))
#Mat.Elastic(table=((210000, 0.3), ))
#Mat.Plastic(table=((186.2712, 0),(225.6347, 0.005),(246.211, 0.01),(260.697, 0.015),(272.0399, 0.02),(281.4356, 0.025),(289.4961, 0.03),(296.5791, 0.035),(302.9127, 0.04),(308.652, 0.045),(313.9075, 0.05),(318.7608, 0.055),(323.274, 0.06),(327.4956, 0.065),(331.464, 0.07),(335.2105, 0.075),(338.7607, 0.08),(342.136, 0.085),(345.3541, 0.09),(348.4305, 0.095),(351.3781, 0.1),(354.2082, 0.105),(356.9308, 0.11),(359.5544, 0.115),(362.0866, 0.12),(364.5341, 0.125),(366.903, 0.13),(369.1985, 0.135),(371.4256, 0.14),(373.5885, 0.145),(375.6912, 0.15),(377.7373, 0.155),(379.73, 0.16),(381.6723, 0.165),(383.5669, 0.17),(385.4163, 0.175),(387.2228, 0.18),(388.9886, 0.185),(390.7156, 0.19),(392.4057, 0.195),(394.0605, 0.2)))
#Hutprofil.HomogeneousSolidSection(material='Mat', name='Section Blech', thickness=None)
#Blech.SectionAssignment(offset=0.0, offsetField='', offsetType=MIDDLE_SURFACE,region=Region(cells=Blech.cells), sectionName='Section Blech', thicknessAssignment=FROM_SECTION)
#
Hutprofil.ImplicitDynamicsStep(name='entry',previous='Initial',description='entry', nlgeom=ON)
Hutprofil.ContactProperty('Kontakt_nofric')
Hutprofil.interactionProperties['Kontakt_nofric'].NormalBehavior(allowSeparation=ON, clearanceAtZeroContactPressure=0.0,constraintEnforcementMethod=AUGMENTED_LAGRANGE, contactStiffness=1000,contactStiffnessScaleFactor=1.0, pressureOverclosure=HARD)
Hutprofil.interactionProperties['Kontakt_nofric'].TangentialBehavior(absoluteDistance=0.01, dependencies=0, directionality=ISOTROPIC,elasticSlipStiffness=None, formulation=PENALTY, maximumElasticSlip=ABSOLUTE_DISTANCE, pressureDependency=OFF, shearStressLimit=None,slipRateDependency=OFF, table=((0, ), ), temperatureDependency=OFF)
#
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_FS_OW, name='Kontakt FS_OW', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_FS_UW, name='Kontakt FS_UW', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_O_R1, name='Kontakt S1_O_R1_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_O_R2, name='Kontakt S1_O_R2_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_O_R3, name='Kontakt S1_O_R3_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_O_R4, name='Kontakt S1_O_R4_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_O_R5, name='Kontakt S1_O_R5_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_O_R6, name='Kontakt S1_O_R6_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_U_R1, name='Kontakt S1_U_R1_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_U_R2, name='Kontakt S1_U_R2_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S1_U_R3, name='Kontakt S1_U_R3_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_O_R1, name='Kontakt S2_O_R1_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_O_R2, name='Kontakt S2_O_R2_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_O_R3, name='Kontakt S2_O_R3_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_O_R4, name='Kontakt S2_O_R4_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_O_R5, name='Kontakt S2_O_R5_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_U_R1, name='Kontakt S2_U_R1_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_U_R2, name='Kontakt S2_U_R2_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S2_U_R3, name='Kontakt S2_U_R3_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_O_R1, name='Kontakt S3_O_R1_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_O_R2, name='Kontakt S3_O_R2_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_O_R3, name='Kontakt S3_O_R3_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_O_R4, name='Kontakt S3_O_R4_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_O_R5, name='Kontakt S3_O_R5_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_U_R1, name='Kontakt S3_U_R1_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_U_R2, name='Kontakt S3_U_R2_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S3_U_R3, name='Kontakt S3_U_R3_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S4_O_R1, name='Kontakt S4_O_R1_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S4_O_R2, name='Kontakt S4_O_R2_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S4_O_R3, name='Kontakt S4_O_R3_entry', secondary=RF_Blech_OW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S4_U_R1, name='Kontakt S4_U_R1_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S4_U_R2, name='Kontakt S4_U_R2_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#Hutprofil.SurfaceToSurfaceContactStd(adjustMethod=NONE,clearanceRegion=None, createStepName='entry', datumAxis=None,initialClearance=OMIT, interactionProperty='Kontakt_nofric', main=RF_S4_U_R3, name='Kontakt S4_U_R3_entry', secondary=RF_Blech_UW, sliding=FINITE, thickness=ON)
#
Hutprofil.DisplacementBC(name='BC_FS_OW', createStepName='entry',region=RRP_FS_OW, u1=0.0, u2=0.0, u3=0.0, ur1=0.0, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_FS_UW', createStepName='entry',region=RRP_FS_UW, u1=0.0, u2=0.0, u3=0.0, ur1=0.0, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R1', createStepName='entry',region=RRP_S1_O_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R2', createStepName='entry',region=RRP_S1_O_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R3', createStepName='entry',region=RRP_S1_O_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R4', createStepName='entry',region=RRP_S1_O_R4, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R5', createStepName='entry',region=RRP_S1_O_R5, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R6', createStepName='entry',region=RRP_S1_O_R6, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_U_R1', createStepName='entry',region=RRP_S1_U_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_U_R2', createStepName='entry',region=RRP_S1_U_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_U_R3', createStepName='entry',region=RRP_S1_U_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R1', createStepName='entry',region=RRP_S2_O_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R2', createStepName='entry',region=RRP_S2_O_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R3', createStepName='entry',region=RRP_S2_O_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R4', createStepName='entry',region=RRP_S2_O_R4, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R5', createStepName='entry',region=RRP_S2_O_R5, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_U_R1', createStepName='entry',region=RRP_S2_U_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_U_R2', createStepName='entry',region=RRP_S2_U_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_U_R3', createStepName='entry',region=RRP_S2_U_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R1', createStepName='entry',region=RRP_S3_O_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R2', createStepName='entry',region=RRP_S3_O_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R3', createStepName='entry',region=RRP_S3_O_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R4', createStepName='entry',region=RRP_S3_O_R4, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R5', createStepName='entry',region=RRP_S3_O_R5, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_U_R1', createStepName='entry',region=RRP_S3_U_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_U_R2', createStepName='entry',region=RRP_S3_U_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_U_R3', createStepName='entry',region=RRP_S3_U_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_O_R1', createStepName='entry',region=RRP_S4_O_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_O_R2', createStepName='entry',region=RRP_S4_O_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_O_R3', createStepName='entry',region=RRP_S4_O_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_U_R1', createStepName='entry',region=RRP_S4_U_R1, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_U_R2', createStepName='entry',region=RRP_S4_U_R2, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_U_R3', createStepName='entry',region=RRP_S4_U_R3, u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=0.0,ur3=0.0, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R1_entry', createStepName='entry',region=RRP_S1_O_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R2_entry', createStepName='entry',region=RRP_S1_O_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R3_entry', createStepName='entry',region=RRP_S1_O_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R4_entry', createStepName='entry',region=RRP_S1_O_R4, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R5_entry', createStepName='entry',region=RRP_S1_O_R5, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_O_R6_entry', createStepName='entry',region=RRP_S1_O_R6, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_U_R1_entry', createStepName='entry',region=RRP_S1_U_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_U_R2_entry', createStepName='entry',region=RRP_S1_U_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S1_U_R3_entry', createStepName='entry',region=RRP_S1_U_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R1_entry', createStepName='entry',region=RRP_S2_O_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R2_entry', createStepName='entry',region=RRP_S2_O_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R3_entry', createStepName='entry',region=RRP_S2_O_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R4_entry', createStepName='entry',region=RRP_S2_O_R4, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_O_R5_entry', createStepName='entry',region=RRP_S2_O_R5, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_U_R1_entry', createStepName='entry',region=RRP_S2_U_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_U_R2_entry', createStepName='entry',region=RRP_S2_U_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S2_U_R3_entry', createStepName='entry',region=RRP_S2_U_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R1_entry', createStepName='entry',region=RRP_S3_O_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R2_entry', createStepName='entry',region=RRP_S3_O_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R3_entry', createStepName='entry',region=RRP_S3_O_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R4_entry', createStepName='entry',region=RRP_S3_O_R4, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_O_R5_entry', createStepName='entry',region=RRP_S3_O_R5, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_U_R1_entry', createStepName='entry',region=RRP_S3_U_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_U_R2_entry', createStepName='entry',region=RRP_S3_U_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S3_U_R3_entry', createStepName='entry',region=RRP_S3_U_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_O_R1_entry', createStepName='entry',region=RRP_S4_O_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_O_R2_entry', createStepName='entry',region=RRP_S4_O_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_O_R3_entry', createStepName='entry',region=RRP_S4_O_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_U_R1_entry', createStepName='entry',region=RRP_S4_U_R1, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_U_R2_entry', createStepName='entry',region=RRP_S4_U_R2, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
Hutprofil.DisplacementBC(name='BC_S4_U_R3_entry', createStepName='entry',region=RRP_S4_U_R3, u1=UNSET, u2=UNSET, u3=UNSET, ur1=0.0, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
#
#Blech.DatumPlaneByPrincipalPlane(offset=340, principalPlane=XYPLANE)
#xy_ebene1=Blech.datums.keys()[-1]
#Blech.PartitionCellByDatumPlane(cells=Blech.cells, datumPlane=Blech.datums[xy_ebene1])
#Blech.DatumPlaneByPrincipalPlane(offset=260, principalPlane=XYPLANE)
#xy_ebene2=Blech.datums.keys()[-1]
#Blech.PartitionCellByDatumPlane(cells=Blech.cells, datumPlane=Blech.datums[xy_ebene2])
#Blech.DatumPlaneByPrincipalPlane(offset=380, principalPlane=XYPLANE)
#xy_ebene3=Blech.datums.keys()[-1]
#Blech.PartitionCellByDatumPlane(cells=Blech.cells, datumPlane=Blech.datums[xy_ebene3])
#Blech.DatumPlaneByPrincipalPlane(offset=220, principalPlane=XYPLANE)
#xy_ebene4=Blech.datums.keys()[-1]
#Blech.PartitionCellByDatumPlane(cells=Blech.cells, datumPlane=Blech.datums[xy_ebene4])
#cAuswertestreifen=Blech.cells.findAt((4,0,300),)
#Blech.DatumPlaneByPrincipalPlane(offset=5, principalPlane=YZPLANE)
#yz_ebene2=Blech.datums.keys()[-1]
#Blech.PartitionCellByDatumPlane(cells=cAuswertestreifen, datumPlane=Blech.datums[yz_ebene2])
#cAuswertestreifen=Blech.cells.findAt((14,0,300),)
#Blech.DatumPlaneByPrincipalPlane(offset=15, principalPlane=YZPLANE)
#yz_ebene3=Blech.datums.keys()[-1]
#Blech.PartitionCellByDatumPlane(cells=cAuswertestreifen, datumPlane=Blech.datums[yz_ebene3])
#cAuswertestreifen=Blech.cells.findAt((24,0,300),)
#Blech.DatumPlaneByPrincipalPlane(offset=25, principalPlane=YZPLANE)
#yz_ebene4=Blech.datums.keys()[-1]
#Blech.PartitionCellByDatumPlane(cells=cAuswertestreifen, datumPlane=Blech.datums[yz_ebene4])
#F_Blech_back=Blech.faces.findAt(coordinates=((11,0.75,0,),))
#Blech.PartitionFaceByDatumPlane(datumPlane=Blech.datums[yz_ebene4], faces=F_Blech_back)
#F_Blech_front=Blech.faces.findAt(coordinates=((11,0.75,600,),))
#Blech.PartitionFaceByDatumPlane(datumPlane=Blech.datums[yz_ebene4], faces=F_Blech_front)
#elemType1 = mesh.ElemType(elemCode=C3D8I, elemLibrary=STANDARD,secondOrderAccuracy=OFF, distortionControl=DEFAULT)
#Blech.setElementType(regions=(Blech.cells,), elemTypes=(elemType1, ))
#Blech.seedPart(size=1, minSizeFactor=0.1)
#Blech.generateMesh()
#F_Blech_back=F_Blech.findAt(coordinates=((539,352.25,-630,),))
#RF_Blech_back=regionToolset.Region(faces=F_Blech_back)
#Hutprofil.DisplacementBC(name='BC_ylock', createStepName='entry',region=RF_Blech_back, u1=UNSET, u2=0.0, u3=UNSET, ur1=UNSET, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
#F_Blech_front=F_Blech.findAt(coordinates=((539,352.25,-30,),))
#RF_Blech_front=regionToolset.Region(faces=F_Blech_front)
#Hutprofil.DisplacementBC(name='BC_zstart_entry', createStepName='entry',region=RF_Blech_front, u1=UNSET, u2=UNSET, u3=40, ur1=UNSET, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
#Hutprofil.DisplacementBC(name='BC_ylock_entry', createStepName='entry',region=RF_Blech_front, u1=UNSET, u2=0.0, u3=UNSET, ur1=UNSET, ur2=UNSET,ur3=UNSET, amplitude=UNSET, fixed=OFF, distributionType=UNIFORM,fieldName='', localCsys=None)
